blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blogs/', views.blogs_list, name='blogs_list'),
    path('blogs/<int:blog_id>/', views.entries_list, name='entries_list'),
    path('blogs/<int:blog_id>/<int:entry_id>/', views.entry, name ='entry'),
    path('new_blog/', views.new_blog, name = 'new_blog'),
    path('blogs/new_entry/<int:blog_id>', views.new_entry, name='new_entry'),
    path('blogs/edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('blog/edit_blog/<int:blog_id>', views.edit_blog, name='edit_blog'),
    path('blogs/<int:entry_id>/delete_entry', views.delete_entry, name='delete_entry'),
    path('blogs/<int:blog_id>/delete_blog', views.delete_blog, name='delete_blog'),
    path('blogs/<int:entry_id>/comment_entry', views.comment_entry, name='comment_entry'),
    path('blogs/<int:comment_id>/comment_response', 
        views.comment_response, name='comment_response'),
    path('blogs/<int:comment_id>/delete_comment', 
        views.delete_comment, name='delete_comment'),
    path('blogs/<int:response_id>/delete_response', 
        views.delete_response, name='delete_response'),
    path('blogs/search_blogs', views.search_blogs, name='search_blogs'),
    
]

collaborators/urls.py
from django.urls import path
from . import views

app_name = 'collaborators'
urlpatterns = [
      path('new_collab_request/<int:blog_id>/<int:target_id>', 
            views.new_collab_request, name='new_collab_request'),
      path('remove_collab/<int:blog_id>,<int:target_id>', views.remove_collab,
           name='remove_collab'),
      path('accept_collab_request/<int:request_id>', 
            views.accept_collab_request, name='accept_collab_request'),
      path('decline_collab_request/<int:request_id>', 
            views.decline_collab_request, name='decline_collab_request'),
      path('cancel_collab_request/<int:request_id>', 
            views.cancel_collab_request, name='cancel_collab_request'),
      path('collab_requests_page/', 
            views.collab_requests_page, name='collab_requests_page'),
      path('add_collaborator/<int:blog_id>/', 
            views.add_collab_page, name='add_collab_page'),
      path('remove_collaborator/<int:blog_id>/', 
            views.remove_collab_page, name='remove_collab_page'),
      
]

www/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('accounts.urls')),
    path('', include('friends.urls')),
    path('', include('collaborators.urls')),
    path('', include('notifications.urls')),
    path('', include('emails.urls')),
    path('tinymce/', include('tinymce.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

collaborators/models.py
from django.db import models
from blog.models import Blog
from django.conf import settings

User = settings.AUTH_USER_MODEL

class CollabList(models.Model):
    """A list of people who can create entries in blogs from other author"""
    blog = models.OneToOneField(Blog, on_delete=(models.CASCADE), related_name='collaborators')
    collab_list = models.ManyToManyField(User, blank=True, related_name='collaborations')

    def add_collaborator(self, account):
        """Adds a new collaborator"""
        if account not in self.collab_list.all():
            self.collab_list.add(account)

    def remove_collaborator(self,account):
        """Eliminates an account from the collaborators list"""
        if account in self.collab_list.all():
            self.collab_list.remove(account)


class CollabRequest(models.Model):
    """Manages collaboration requests"""
    blog = models.ForeignKey(Blog, on_delete=(models.CASCADE), 
                            related_name='collab_requests')
    sender = models.ForeignKey(User, on_delete=(models.CASCADE), 
                            related_name = "collab_requests_sent")
    receiver = models.ForeignKey(User, on_delete=(models.CASCADE), 
                            related_name = "collab_requests_received")
    timestamp = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def accept(self):
        """adds the receiver to blog collaborators and makes request inactive"""
        blog_collabs = CollabList.objects.get(blog=self.blog)
        if blog_collabs:
            blog_collabs.add_collaborator(self.receiver)
        self.is_active = False
        self.save()

    def decline(self):
        """makes request inactive (this action is taken by the receiver)"""
        self.is_active = False
        self.save()
    
    def cancel(self):
        """makes request inactive (this action is taken by the sender)"""
        self.is_active = False
        self.save()

    def renew(self):
        """makes request active again"""
        self.is_active = True
        self.save()

collaborators/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from blog.models import Blog
from django.contrib.auth import get_user_model
from .models import CollabRequest, CollabList
from notifications.models import CommentNotification, NewEntryNotification
from django.contrib import messages
from django.http import Http404

User = get_user_model()

@login_required
def add_collab_page(request, blog_id):
    user = User.objects.get(id=request.user.id)
    user_friends = user.friends_list.friends.all()
    blog = Blog.objects.get(id=blog_id)
    context = {
        'user': user,
        'user_friends': user_friends,
        'blog': blog,
    }
    check_author(request, blog.author)
    return render(request, 'collaborators/add_collab_page.html', context)

@login_required
def remove_collab_page(request, blog_id):
    user = User.objects.get(id=request.user.id)
    blog = Blog.objects.get(id=blog_id)
    collabs = CollabList.objects.get(blog=blog).collab_list.all()
    context = {
        'user': user,
        'blog': blog,
        'collabs': collabs,
    }
    check_author(request, blog.author)
    return render(request, 'collaborators/remove_collab_page.html', context)


@login_required
def new_collab_request(request, blog_id, target_id):
    request_blog = Blog.objects.get(id=blog_id)
    blog_collaborators_list = CollabList.objects.get(blog=request_blog).collab_list.all()
    request_sender = request.user
    request_receiver = User.objects.get(id=target_id)
    request_sender_friends = request_sender.friends_list.friends.all()
    existing_request = CollabRequest.objects.filter(
        blog=request_blog, sender= request_sender, receiver=request_receiver,
        is_active=True)
    inactive_request = CollabRequest.objects.filter(
        blog=request_blog, sender= request_sender, receiver=request_receiver,
        is_active=False).first()
    next_page = request.POST.get("next")

    if request_sender != request_blog.author:
        messages.error(request, f'solo puedes invitar colaboradores a blogs de los que seas autor', extra_tags="collabs")
        return redirect(next_page or "blog:blogs_list")

    if request_sender == request_receiver:
        messages.error(request, f'No puedes invitarte a colaborar a ti mismo', extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)

    if request_receiver not in request_sender_friends:
        messages.info(request, 
            f'{request_receiver} no está en tu lista de amigos. Solo puedes invitar a tus amigos a colaborar', 
            extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)
    
    if request_receiver in blog_collaborators_list:
        messages.info(request, f'{request_receiver} ya está en la lista de colaboradores de este blog', extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)
    
    if existing_request.exists():
        messages.info(request, f'Ya has enviado una solicitud de colaboración a {request_receiver}', extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)
    
    if inactive_request:
        inactive_request.renew()
        messages.success(request, f'¡Has invitado a {request_receiver} a colaborar en tu blog', extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)
    
    else:
        CollabRequest.objects.get_or_create(
            blog=request_blog, sender= request_sender, receiver=request_receiver)
        messages.success(request, f'¡Has invitado a {request_receiver} a colaborar en tu blog', extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)


@login_required
def remove_collab(request, blog_id,target_id):
    blog = Blog.objects.get(id=blog_id)
    list = CollabList.objects.get(blog=blog)
    collaborators = list.collab_list.all()
    target = User.objects.get(id=target_id)
    next_page = request.POST.get("next")
    check_author(request, blog.author)

    if target not in collaborators:
        messages.error(request, f'{target} no está en la lista de colaboradores del blog',
                       extra_tags='collabs')
        return redirect(next_page or "blog:entries_list", blog.id)
    
    if target not in collaborators:
        messages.error(request, f'{target} no está en la lista de colaboradores del blog',
                       extra_tags='collabs')
        return redirect(next_page or "blog:entries_list", blog.id)
    
    list.remove_collaborator(target)
    messages.success(request, f'Has eliminado a {target} de la lista de colaboradores',
                     extra_tags='collabs')
    return redirect(next_page or "blog:entries_list", blog.id)


@login_required
def accept_collab_request(request, request_id):
    current_request = CollabRequest.objects.get(id=request_id)
    request_blog = current_request.blog
    next_page = request.POST.get('next')
    sender_friends = current_request.sender.friends_list.friends.all()

    if request_blog.author == request.user:
        messages.error(request, '¡No puedes ser colaborador de tu propio blog!', extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)
    
    if request.user != current_request.receiver:
        messages.error(request, '¡Ups! Parece que esta solicitud no iba dirigida a ti', extra_tags="collabs")
        return redirect(next_page or "blog:entries_list", request_blog.id)
    
    if request.user not in sender_friends:
        messages.error(request, f'¡Ups! parece que no estás en la lista de amigos de {current_request.sender}',
                       extra_tags='collabs')
        current_request.cancel()
        return redirect(next_page or "blog:entries_list", request_blog.id)
    
    current_request.accept()
    messages.success(request, f'¡Ahora puedes publicar en el blog "{current_request.blog}"!', extra_tags="collabs")
    return redirect(next_page or "blog:entries_list", request_blog.id)


@login_required
def decline_collab_request(request, request_id):
    current_request = CollabRequest.objects.get(id=request_id)
    request_blog = current_request.blog
    next_page = request.POST.get('next')

    current_request.decline()
    messages.success(request, f'Has rechazado la solicitud de colaboración de {current_request.sender}', extra_tags="collabs")
    return redirect(next_page or "blog:entries_list", request_blog.id)


@login_required
def cancel_collab_request(request, request_id):
    current_request = CollabRequest.objects.get(id=request_id)
    request_blog = current_request.blog
    next_page = request.POST.get('next')

    current_request.cancel()
    messages.success(request, f'Has cancelado la solicitud de colaboración a {current_request.receiver}', extra_tags="collabs")
    return redirect(next_page or "blog:entries_list", request_blog.id)


@login_required
def collab_requests_page(request):
    user = User.objects.get(id=request.user.id)
    user_collab_requests = CollabRequest.objects.filter(receiver=user, is_active=True)
    sent_collab_requests = CollabRequest.objects.filter(sender=user, is_active=True)
    comment_notifications = CommentNotification.objects.filter(target=request.user)
    entry_notifications = NewEntryNotification.objects.filter(target=request.user)
    
    
    context={
        'list_user': user,
        'user_collab_requests' : user_collab_requests,
        'sent_collab_requests' : sent_collab_requests,
        'entry_notifications' : entry_notifications,
        'comment_notifications' : comment_notifications,
    }
    return render(request, 'collaborators/collab_requests.html', context)


def check_author(request, author):
    if author != request.user:
        raise Http404
    

collaborators/templates/collaborators/add_collab_page.html
{% extends 'blog/layout.html' %}

{% block page_header %}


{% endblock page_header %}

{% block content %}

{% if messages %}
    <div>
        {% for message in messages %}
            {% if 'collabs' in message.tags %}
                <div class="alert alert-{{ message.level_tag }}">
                    {{message}}
                </div>
            {% endif %}                    
        {% endfor %}
    </div>
{% endif %}

<div class="px-1 px-md-4 py-4 d-flex flex-column centered">
    <div class="centered pb-1">
        <h3>  Añadir colaborador </h3>
    </div>
</div>

<div class="px-1 px-md-4 py-4 d-flex flex-column blackboard col-md-8 mx-auto">
    <p class="me-auto p-2 blog-options">
        <a href="{% url 'blog:entries_list' blog.id %}">&laquo; Atrás </a>
    </p>
    <div class="centered pb-3">
        <h4>Elige a alguien de tu lista de amigos</h4>
    </div>
    {% for friend in user_friends %}
        <div class="friends-list pb-2 pt-2">
            <div class="friends-row border-bottom pb-2">
                <div>
                    <p>{{friend}}</p>
                </div>
                <div class="friends-row-buttons">
                    <form action="{% url 'collaborators:new_collab_request' blog.id friend.id %}"
                     method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class= "friends-row-button ms-auto" 
                            type="submit">Invitar</button>
                    </form>
                </div>
            </div>
        </div>
    {% empty %}
    <p>Debes tener a alguien en tu lista de amigos para enviarle una solicitud de colaboración</p>
    {% endfor %}
</div>

{% endblock content %}

collaborators/templates/collaborators/collab_requests.html
{% extends 'blog/layout.html' %}

{% block page_header %}


{% endblock page_header %}

{% block content %}

{% if messages %}
    <div>
        {% for message in messages %}
            {% if 'collabs' in message.tags %}
                <div class="alert alert-{{ message.level_tag }}">
                    {{message}}
                </div>
            {% endif %}                    
        {% endfor %}
    </div>
{% endif %}

<div class="px-1 px-md-4 py-4 d-flex flex-column centered">
    
        <h3>  Solicitudes de colaboración </h3>
    
</div>

<div class="p-3 mb-1 blackboard pb-3 col-md-6 mx-auto">
    <div class="centered pb-3">
        <h5>Recibidas</h5>
    </div>
    {% for collab_request in user_collab_requests %}
        <div class="friends-list pb-2 pt-2">
            <div class="friends-row border-bottom pb-2">
                <div>
                    <p>¡{{collab_request.sender}} quiere que colabores en su blog "{{collab_request.blog}}"!</p>
                </div>
                <div class="friends-row-buttons">
                    <form action="{% url 'collaborators:accept_collab_request' collab_request.id  %}"
                     method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class= "friends-row-button ms-auto" 
                            type="submit">Aceptar</button>
                    </form>
                    <form action="{% url 'collaborators:decline_collab_request' collab_request.id %}" 
                    method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class= "friends-row-button ms-auto" 
                            type="submit">Rechazar</button>
                    </form>
                </div>
            </div>
        </div>
    {% empty %}
        <p>No tienes solicitudes de colaboración pendientes</p>
    {% endfor %}
    <div class="centered pb-3">
        <h5>Enviadas</h5>
    </div>
    {% for collab_request in sent_collab_requests %}
        <div class="friends-list pb-2 pt-2">
            <div class="friends-row border-bottom pb-2">
                <div>
                    <p>Has invitado a {{collab_request.receiver}} a colaborar en "{{collab_request.blog}}"</p>
                </div>
                <div class="friends-row-buttons">
                    <form action="{% url 'collaborators:cancel_collab_request' collab_request.id %}" 
                    method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class= "friends-row-button ms-auto" 
                            type="submit">Cancelar</button>
                    </form>
                </div>
            </div>
        </div>
    {% empty %}
        <p>No tienes solicitudes de colaboración pendientes</p>
    {% endfor %}
</div>

{% endblock content %}

collaborators/templates/collaborators/remove_collab_page.html
{% extends 'blog/layout.html' %}

{% block page_header %}


{% endblock page_header %}

{% block content %}

{% if messages %}
    <div>
        {% for message in messages %}
            {% if 'collabs' in message.tags %}
                <div class="alert alert-{{ message.level_tag }}">
                    {{message}}
                </div>
            {% endif %}                    
        {% endfor %}
    </div>
{% endif %}

<div class="px-1 px-md-4 py-4 d-flex flex-column centered">
        <h3>  Eliminar colaborador </h3>
</div>

<div class="p-3 mb-1 blackboard mx-auto col-md-6">
    <p class="me-auto p-2 blog-options">
        <a href="{% url 'blog:entries_list' blog.id %}">&laquo; Atrás </a>
    </p>
    <div class="centered pb-3">
        <h4>Elige al colaborador al que quieres eliminar</h4>
    </div>
    {% for collab in collabs %}
        <div class="friends-list pb-2 pt-2">
            <div class="friends-row border-bottom pb-2">
                <div>
                    <p>{{collab}}</p>
                </div>
                <div class="friends-row-buttons">
                    <form action="{% url 'collaborators:remove_collab' blog.id collab.id %}"
                     method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class= "friends-row-button ms-auto" 
                            type="submit">Eliminar</button>
                    </form>
                </div>
            </div>
        </div>
    {% empty %}
    <p>Este blog no tiene colaboradores que eliminar</p>
    {% endfor %}
</div>

{% endblock content %}