accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [ 
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user_profile/<int:user_id>', views.user_profile, name='user_profile'),
    path('edit_profile/<int:user_id>', views.edit_profile, name='edit_profile'),
    path('activate_account/<str:uid_b64>/<str:token>/', views.activate_account, name='activate_account'),
    path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
    path('reset_password/<str:uid_b64>/<str:token>/', views.reset_password, name='reset_password'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blogs/', views.blogs_list, name='blogs_list'),
    path('blogs/<int:blog_id>/', views.entries_list, name='entries_list'),
    path('blogs/<int:blog_id>/<int:entry_id>/', views.entry, name ='entry'),
    path('new_blog/', views.new_blog, name = 'new_blog'),
    path('blogs/new_entry/<int:blog_id>', views.new_entry, name='new_entry'),
    path('blogs/edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    path('blog/edit_blog/<int:blog_id>', views.edit_blog, name='edit_blog'),
    path('blogs/<int:entry_id>/delete_entry', views.delete_entry, name='delete_entry'),
    path('blogs/<int:blog_id>/delete_blog', views.delete_blog, name='delete_blog'),
    path('blogs/<int:entry_id>/comment_entry', views.comment_entry, name='comment_entry'),
    path('blogs/<int:comment_id>/comment_response', 
        views.comment_response, name='comment_response'),
    path('blogs/<int:comment_id>/delete_comment', 
        views.delete_comment, name='delete_comment'),
    path('blogs/<int:response_id>/delete_response', 
        views.delete_response, name='delete_response'),
    path('blogs/search_blogs', views.search_blogs, name='search_blogs'),
    
]

collaborators/urls.py
from django.urls import path
from . import views

app_name = 'collaborators'
urlpatterns = [
      path('new_collab_request/<int:blog_id>/<int:target_id>', 
            views.new_collab_request, name='new_collab_request'),
      path('remove_collab/<int:blog_id>,<int:target_id>', views.remove_collab,
           name='remove_collab'),
      path('accept_collab_request/<int:request_id>', 
            views.accept_collab_request, name='accept_collab_request'),
      path('decline_collab_request/<int:request_id>', 
            views.decline_collab_request, name='decline_collab_request'),
      path('cancel_collab_request/<int:request_id>', 
            views.cancel_collab_request, name='cancel_collab_request'),
      path('collab_requests_page/', 
            views.collab_requests_page, name='collab_requests_page'),
      path('add_collaborator/<int:blog_id>/', 
            views.add_collab_page, name='add_collab_page'),
      path('remove_collaborator/<int:blog_id>/', 
            views.remove_collab_page, name='remove_collab_page'),
      
]

friends/urls.py
from django.urls import path
from . import views

app_name = 'friends'

urlpatterns = [
    path('new_friend_request/<int:target_id>/', views.new_friend_request, name='new_friend_request'),
    path('friends/friends_page/', views.friends_page, name='friends_page'),
    path('friends/accept_request/<int:fr_request_id>', views.accept_request, name='accept_request'),
    path('friends/decline_request/<int:fr_request_id>', views.decline_request, name='decline_request'),
    path('friends/end_friendship/<int:removee_id>', views.end_friendship, name='end_friendship'),
    path('friends/search_friends/', views.search_friends, name='search_friends'),
               ]

notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'

urlpatterns = [
    path('activity/', views.activity, name='activity'),
]
               

www/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('accounts.urls')),
    path('', include('friends.urls')),
    path('', include('collaborators.urls')),
    path('', include('notifications.urls')),
    path('', include('emails.urls')),
    path('tinymce/', include('tinymce.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

from cloudinary import CloudinaryImage
from cloudinary.models import CloudinaryField



User = get_user_model()

class Blog(models.Model):
    text = models.CharField(max_length=140)
    about = models.CharField(max_length = 200, blank=True,)
    banner = CloudinaryField('banner', blank=True, null=True, transformation=[
            {
            'width': 2000,
            'height': 2000,
            'crop': 'limit',
            'quality': 'auto',
            }
        ]
    )
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    
    def add_collaborator(self, account):
        if account not in self.collaborators:
            self.collaborators.add(account)
            self.save()

    def banner_url(self):

        public_id = self.banner.public_id if self.banner else 'libro-pasando-paginas_pccza0_c_fill_w_240_h_135_ar_16_9_nqefmh'
        return CloudinaryImage(public_id).build_url(
            width=288,
            aspect_ratio='16:9', 
            crop='fill',
            gravity='auto', 
            fetch_format='auto',
            quality='auto',
            )
    
        
    
class Entry(models.Model):
    class Meta():
        verbose_name_plural = 'Entries'

    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=(models.CASCADE), related_name="collab_entries")
    banner = CloudinaryField('banner', blank=True, null=True, transformation=[
            {
            'width': 2000,
            'height': 2000,
            'crop': 'limit',
            'quality': 'auto',
            }
        ]
    )
                                
    def banner_card_url(self):

        public_id = self.banner.public_id
        return CloudinaryImage(public_id).build_url(
            width=288,
            aspect_ratio='16:9', 
            crop='fill',
            gravity='auto', 
            fetch_format='auto',
            quality='auto',
            )
    
    
    def __str__(self):
        return self.title
    
    
class EntryComment(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text
    

class CommentResponse(models.Model):
    comment = models.ForeignKey(EntryComment, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.conf import settings
from django.http import Http404
import bleach


from .models import Blog, Entry, EntryComment, CommentResponse
from .forms import BlogForm, EntryForm, EntryCommentForm, CommentResponseForm

User = get_user_model()

def home(request):
    return render(request, 'blog/home.html')


def blogs_list(request):
    blogs = Blog.objects.all()
    fallback = []
    user_blogs = (blogs.filter(author=request.user) 
                if request.user.is_authenticated 
                else Blog.objects.none())
    collaborating_blogs = (blogs.filter(collaborators__collab_list=request.user) 
                        if request.user.is_authenticated else fallback)
    friends_blogs = (blogs.filter(author__friends_list__friends=request.user) 
                     if request.user.is_authenticated else fallback)
    other_blogs = (blogs.exclude(author=request.user)
                   .exclude(collaborators__collab_list=request.user)
                   .exclude(author__friends_list__friends=request.user)
                   if request.user.is_authenticated else blogs)
    
    context = {'blogs': blogs, 
               'user_blogs': user_blogs, 
               'other_blogs':other_blogs,
               'collaborating_blogs': collaborating_blogs,
               'friends_blogs': friends_blogs}
    
    return render (request, 'blog/blogs_list.html', context)


def entries_list(request,blog_id):
    blog = Blog.objects.get(id=blog_id)
    entries = blog.entry_set.order_by('-date_added')
    blog_collabs = blog.collaborators.collab_list.all()
    collabs_len = len(blog_collabs)
    collabs_word = "Colaboradores" if collabs_len != 1 else "Colaborador"
    collabs_phrase = f'{collabs_len} {collabs_word}'
    context = {'blog': blog, 
               'entries': entries, 
               "blog_collabs": blog_collabs,
               'collabs_phrase': collabs_phrase,}
    
    return render(request, 'blog/entries_list.html', context)


def entry(request,blog_id,entry_id):
    blog = Blog.objects.get(id=blog_id)
    entry = Entry.objects.get(id=entry_id)
    entries = Entry.objects.all()
    entry_comments = entry.entrycomment_set.order_by('-date_added')
    comments = entry_comments.filter(entry=entry)
    comments_len = len(comments)
    comments_word = "Comentarios" if comments_len != 1 else "Comentario"
    if request.method != 'POST':
        form = EntryCommentForm()
    else:
        form = EntryCommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.entry = entry
            new_comment.author = request.user
            new_comment.save()
            return redirect('blog:entry', blog.id, entry.id)
    context= {
        'blog': blog,
        'entry': entry,
        'entries': entries,
        'comments': comments,
        'comments_len': comments_len,
        'comments_word': comments_word,
        'form':form,
        'author_avatar': entry.author.avatar_url(size=50),
    }
    return render(request, 'blog/entry.html', context)


@login_required
def new_blog(request):
    if not request.user.is_active:
        raise Http404
    if request.method != 'POST':
        form = BlogForm()
    else:
        form = BlogForm(data = request.POST, files=request.FILES)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.author = request.user
            new_blog.save()
            return redirect('blog:blogs_list')
        
    context = {'form': form,}
    return render(request, 'blog/new_blog.html', context)


@login_required
def new_entry(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    check_author_or_collab(request, blog.author, blog)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.blog = blog
            new_entry.text = clean_content(new_entry.text)
            new_entry.author = request.user
            new_entry.save()
            return redirect('blog:entries_list', blog.id)

    context = {'blog' : blog, 'form': form}
    return render(request, 'blog/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    blog = entry.blog
    check_author_or_collab(request, blog.author, blog)
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST, files=request.FILES)
        if form.is_valid():
            edited_entry= form.save(commit=False)
            edited_entry.text = clean_content(edited_entry.text)
            edited_entry.save()
            return redirect('blog:entry', blog.id, entry.id)
        
    context = {'entry':entry, 'blog':blog, 'form':form}
    return render (request, 'blog/edit_entry.html', context)

@login_required
def edit_blog(request, blog_id):
    
    blog = Blog.objects.get(id=blog_id)
    check_author_or_collab(request, blog.author, blog)
    if request.method != 'POST':
        form = BlogForm(instance=blog)
    else:
        form = BlogForm(instance=blog, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:entries_list', blog.id)
        
    context = {'blog':blog, 
               'form':form}
    return render (request, 'blog/edit_blog.html', context)


@login_required
def comment_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    blog = entry.blog
    if request.method != 'POST':
        form = EntryCommentForm()
    else:
        form = EntryCommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.entry = entry
            new_comment.author = request.user
            new_comment.save()
            return redirect('blog:entry', blog.id, entry.id)
        
    context = {
        'entry':entry, 
        'blog':blog, 
        'form':form}
    return render (request, 'blog/comment_entry.html', context)


@login_required
def comment_response(request, comment_id):
    comment = EntryComment.objects.get(id=comment_id)
    entry = comment.entry
    blog = entry.blog
    if request.method != 'POST':
        form = CommentResponseForm()
    else:
        form = CommentResponseForm(data=request.POST)
        if form.is_valid():
            new_response = form.save(commit=False)
            new_response.comment = comment
            new_response.author = request.user
            new_response.save()
            return redirect('blog:entry', blog.id, entry.id)
        
    context = {'comment': comment, 
               'entry': entry, 
               'blog': blog, 
               'form': form}
    return render (request, 'blog/comment_response.html', context)


@login_required
def delete_entry(request, entry_id):
    if request.method == 'POST':
        entry = Entry.objects.get(id=entry_id)
        blog = entry.blog
        check_author_or_collab(request, blog.author, blog)
        entry.delete()
        return redirect('blog:entries_list', blog.id)
    else:
        return redirect('blog:entries_list', blog.id)
    
    
@login_required
def delete_blog(request, blog_id):
    
    if request.method == 'POST':
        blog = Blog.objects.get(id=blog_id)
        check_author(request, blog.author)
        blog.delete()
        return redirect('blog:blogs_list')
    else:
        return redirect('blog:blogs_list')
    
    
@login_required
def delete_comment(request, comment_id):

    comment = EntryComment.objects.get(id=comment_id)
    entry = comment.entry
    blog = entry.blog
    if request.method == 'POST':
        check_author(request, comment.author)
        comment.delete()
        return redirect('blog:entry', blog.id, entry.id)
    else:
        return redirect('blog:entry', blog.id, entry.id)
    
    
@login_required
def delete_response(request, response_id):
    response = CommentResponse.objects.get(id=response_id)
    comment = response.comment
    entry = comment.entry
    blog = entry.blog
    if request.method == 'POST':
        check_author(request, response.author)
        response.delete()
        return redirect('blog:entry', blog.id, entry.id)
    else:
        return redirect('blog:entry', blog.id, entry.id)
    

def check_author(request, author):
    """checks if the user is the author of the blog. if not, it raises a 404 error"""
    if author != request.user:
        raise Http404
    
    
def check_author_or_collab(request, author, blog):
    """works like ckeck_author but it also allows blog collaborators"""
    if author == request.user or request.user in blog.collaborators.collab_list.all():
        pass
    else:
        raise Http404
    
def clean_content(html):
        return bleach.clean(
            html,
            tags=settings.BLEACH_ALLOWED_TAGS,
            attributes=settings.BLEACH_ALLOWED_ATTRIBUTES,
            css_sanitizer=settings.BLEACH_CSS_SANITIZER,
            strip=True,
        )

def search_blogs(request):
    searched = request.GET.get('searched') or request.POST.get('searched')
    if searched:
        blogs = Blog.objects.filter(text__contains=searched)
        context = {'blogs': blogs,'searched' : searched,}
        return render(request, 'blog/search_blogs.html', context)
    else:
        return render(request, 'blog/search_blogs.html')
        

blog/templates/blog/comment_entry.html
{% extends "blog/layout.html" %}
{% load django_bootstrap5 %}
<head>
    <title>Comenta</title>
</head>
{% block page_header %}

<div class="p-3 mb-1 blackboard centered text-center">
        <h1> Comenta </h1>
</div>
{% endblock page_header %}


{% block content%}

    <div class="p-3 mb-1 blackboard">
        <div class="centered">
            <form action="{% url 'blog:comment_entry' entry.id %}" method='post'>
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    {% bootstrap_button button_type="submit" content="Publicar" %}
            </form>
        </div>
    </div>

{%endblock content%}

blog/templates/blog/entry.html
{% extends "blog/layout.html" %}
{% load django_bootstrap5%}
{% load timeago %}

<title>Home</title>
{% block content%}
<div class="px-1 px-md-4 py-4 d-flex flex-column">
    <div class="friends-row">
        <div>
            <p class="me-auto p-2 blog-options">
                <a href="{% url 'blog:blogs_list' %}">&laquo; Atrás </a>
            </p>
        </div>
        {% if blog.author == request.user or entry.author == request.user %}

            <div class="btn-group ms-auto me-2 me-md-0 py-4">
                <button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <strong> . . . </strong></button>
                
                {% if entry.author == request.user %}
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'blog:edit_entry' entry.id %}">Editar</a></li>
                    {% if blog.author == request.user or entry.author == request.user %}
                        <li><hr class="dropdown-divider"></li>
                        <li><button type="button" class="dropdown-item bg-danger" style="color:white" 
                            data-bs-toggle="modal" data-bs-target="#deleteEntryModal">
                            Eliminar </button></li> 
                    {% endif %}    
                    </ul>
                {% endif %}
            </div>
        {% endif %}
    </div>

    

            <!-- Modal -->
            <div class="modal fade" id="deleteEntryModal" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="modalLabel">¿Eliminar entrada?</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            Estás a punto de eliminar esta entrada del blog. ¿Estás seguro?
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Atrás</button>
                            <form action="{% url 'blog:delete_entry' entry.id %}" method="POST">
                                                {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
    

    <div class="pb-3 centered">
        <h2><strong>{{ entry.title }}</strong></h2>
        <div class="centered-row">
            <a href="{% url 'accounts:user_profile' entry.author.id %}">
                <img class="push-up me-2" src="{{ author_avatar }}">
            </a>
            <p class="message-link"><a href="{% url 'accounts:user_profile' entry.author.id %}">{{ entry.author }}</a>
                - {{ entry.date_added | custom_time_since }} 
            </p>
        </div>
    </div>
    
    <div class="pt-2 pb-3 px-2 px-md-4 bg-light  mx-auto shadowed rounded-4 entry-content">
        <p>{{ entry.text| safe}}</p>
    </div>
   

    <div class= "blog-options p-2 pt-4 border-bottom" style="--bs-border-opacity: .5;">
        <div class="friends-button" id="accordionFlush">
            <div class="accordion-item no-bg">
                <h2 class="accordion-header no-bg" id="flush-headingOne">
                    <button class="accordion-button collapsed no-bg" type="button" 
                    data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" 
                    aria-expanded="false" aria-controls="flush-collapseOne">
                        <p>{{comments_len}} {{comments_word}}</p>
                    </button>
                </h2>
            </div>
        </div>

        <div class="friends-button" id="accordionFlush">
            <div class="accordion-item no-bg">
                <h2 class="accordion-header no-bg" id="flush-headingCom">
                    <button class="accordion-button collapsed no-bg" type="button" 
                    data-bs-toggle="collapse" data-bs-target="#flush-collapseCom" 
                    aria-expanded="false" aria-controls="flush-collapseCom">
                        <p>Comentar</p>
                    </button>
                </h2>
            </div>
        </div>
    </div>

    <div id="flush-collapseCom" class="accordion-collapse collapse no-bg ms-auto"
        aria-labelledby="flush-headingCom" data-bs-parent="#accordionFlush">
        <div class="accordion-body no-bg">
            <div class="p-3 mb-1 blackboard adjusted">
                <div class="centered">
                    <form action="{% url 'blog:comment_entry' entry.id %}" method='post'>
                        {% csrf_token %}
                        {% bootstrap_form form %}
                        {% bootstrap_button button_type="submit" content="Comentar" %}
                    </form>
                </div>
            </div>
        </div>
    </div>    

    <div class= "blog-options p-2 pt-4 border-bottom" style="--bs-border-opacity: .5;">
        <div id="flush-collapseOne" class="accordion-collapse collapse no-bg"
        aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlush">
            <div class="accordion-body no-bg">
                {% for comment in comments %}
                    <div class="border-start">
                        <div class="comment-bar ms-2">
                            <div class="comment-bar me-auto">
                                <a href="{% url 'accounts:user_profile' comment.author.id %}">
                                    <img class="push-up me-2" src="{{ comment.author.avatar_small }}">
                                </a>
                                <p class="text-muted">
                                    <small>{{comment.author}}, {{comment.date_added | custom_time_since}}:</small>   
                                </p>
                            </div>
                        </div>
        
                        <div class="comment-text pb-1 ms-2">
                            <p>{{comment.text | linebreaks}}</p>
                        </div>
                    </div>

                    <div class="blog-options comment-bar border-bottom pb-2">
                        <div style="--bs-border-opacity: .5;">
                            <a href="{% url 'blog:comment_response' comment.id %}"> 
                                Responder </a>
                        </div>

                        <div style="--bs-border-opacity: .5;">
                            {% if comment.author == request.user %}
                                <form action="{% url 'blog:delete_comment' comment.id %}" 
                                method="POST">
                                    {% csrf_token %}
                                    <button type="submit" class="logout-button">Borrar</button>
                                </form>
                            {% endif %}
                        </div>
                    </div>
                
                    {% for response in comment.commentresponse_set.all %}
                        <div class="response-block border-start border-bottom">
                            <div class="comment-bar pb-1">
                                <div class="comment-bar ms-8">
                                    <a href="{% url 'accounts:user_profile' response.author.id %}">
                                        <img class="push-up me-2" src="{{ response.author.avatar_small }}">
                                    </a>
                                    <p class="text-muted">
                                        <small>{{response.author}} respondió:</small>   
                                    </p>
                                    
                                </div>
                            </div>

                            <div class="comment-text pb-2" 
                            style="--bs-border-opacity: .5;">
                                <p>{{response.text | linebreaks}}</p>
                            </div>

                            {% if response.author == request.user %}
                                <div class="right-row">
                                    <form action="{% url 'blog:delete_response' response.id %}" 
                                    method="POST">
                                        {% csrf_token %}
                                        <button type="submit" class="logout-button ms-auto">Borrar</button>
                                    </form>
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% empty %}
                    <p>No hay comentarios aún</p>
                {% endfor %}
            </div>
        </div>  
    </div>
</div>
{%endblock content%}

blog/templates/blog/layout.html
{% load static %}
{% load django_bootstrap5 %}
{% load bootstrap_icons %}

<!DOCTYPE html>
<html lang="es">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Blogoteca</title>
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% bootstrap_javascript %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Vend+Sans:ital,wght@0,300..700;1,300..700&display=swap" rel="stylesheet">
    
</head>
<body>
    <nav class="navbar navbar-expand-md bg-light sticky-top">
    <div class="container-fluid d-flex align-items-center">


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenu" 
    aria-controls="navbarMenut" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMenu">
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'blog:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:blogs_list' %}">Blogs</a>
        </li>
        <li class="nav-item">
          <form class="d-flex adjusted" action="{% url 'blog:search_blogs' %}" method=POST>
            {% csrf_token %} 
            <input class="form-control me-2" type="search" placeholder="Buscar blogs" 
            aria-labels="Buscar blogs" name="searched">
            <button class="friends-row-button mt-1 mb-2" type="submit">{% bs_icon 'search' %}</button>
          </form>
        </li>

      </ul>
    </div>
    
     
      <div class="navbar-right ms-auto d-flex align-items-center gap-2">
        {% if request.user.is_authenticated %}
          {% if request.user.first_name %}
            <p class="nav-item ms-2">
              <span class="navbar-text align-middle">¡Hola, {{request.user.first_name}}!</span>
            </p>
          {% else %}
            <p class="nav-item ms-2">
              <span class="navbar-text">¡Hola, {{request.user.user_name}}!</span>
            </p>
          {% endif %}

        <div class="dropdown">
          <a class="nav-link dropdown-toggle position-relative" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="{{request.user.avatar_small}}">
            {% if unread_notifications_counter > 0 %}
              <span class="position-absolute top-10 start-45 translate-middle p-2 bg-primary border border-light rounded-circle">
                <span class="visually-hidden">New alerts</span>
              </span>
            {% endif %}
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'accounts:user_profile' request.user.id %}">Perfil</a></li>
            <li><a class="dropdown-item d-flex align-items-center justify-content-between" 
              href="{% url 'notifications:activity' %}">Actividad
            {% if unread_notifications_counter > 0 %}
              <span class="badge text-bg-primary rounded-pill">{{ unread_notifications_display }}</span>
            {% endif %}
            </a></li>
            <li><a class="dropdown-item" href="{% url 'friends:friends_page' %}">Amigos</a></li>
            <li><a class="dropdown-item" href="{% url 'collaborators:collab_requests_page' %}">Colaboradores</a></li>
            <li><hr class="dropdown-divider"></li>
            <form action="{% url 'accounts:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">Cerrar sesión</button>
            </form>
          </ul>
        </div>
        {% else %}
        
          <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">Iniciar sesión</a>
        
        
          <a class="nav-link" href="{% url 'accounts:register' %}">Registrarse</a>
        
        {% endif %}
      </div>
      
    </div>
  
</nav>
    {% block page_header %} {% endblock page_header %}
    {% block content%} {% endblock content%}
</body>
</html>