accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [ 
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('user_profile/<int:user_id>', views.user_profile, name='user_profile'),
    path('edit_profile/<int:user_id>', views.edit_profile, name='edit_profile'),
    path('activate_account/<str:uid_b64>/<str:token>/', views.activate_account, name='activate_account'),
    path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
    path('reset_password/<str:uid_b64>/<str:token>/', views.reset_password, name='reset_password'),
]

friends/urls.py
from django.urls import path
from . import views

app_name = 'friends'

urlpatterns = [
    path('new_friend_request/<int:target_id>/', views.new_friend_request, name='new_friend_request'),
    path('friends/friends_page/', views.friends_page, name='friends_page'),
    path('friends/accept_request/<int:fr_request_id>', views.accept_request, name='accept_request'),
    path('friends/decline_request/<int:fr_request_id>', views.decline_request, name='decline_request'),
    path('friends/end_friendship/<int:removee_id>', views.end_friendship, name='end_friendship'),
    path('friends/search_friends/', views.search_friends, name='search_friends'),
               ]

www/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('accounts.urls')),
    path('', include('friends.urls')),
    path('', include('collaborators.urls')),
    path('', include('notifications.urls')),
    path('', include('emails.urls')),
    path('tinymce/', include('tinymce.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

friends/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings



class FriendsList(models.Model):

    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=(models.CASCADE), 
                                related_name='friends_list')
    friends = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='friends')

    def __str__(self):
        return self.user.user_name

    def add_friend(self, account):
        if account not in self.friends.all():
            self.friends.add(account)
        
    def remove_friend(self, account):
        if account in self.friends.all():
            self.friends.remove(account)

    def unfriend(self, removee):
        """
        Terminates a friendship and reciprocally deletes friends from their friends list
        -removee is the object of the terminating friendship
        -self is the one terminating it
        """
        self.remove_friend(removee)
        #queries the user you want to remove from your friends list.
        friends_list= FriendsList.objects.get(user=removee)
        friends_list.remove_friend(self.user)

    def is_mutual_friend(self, friend):
        if friend in self.friends.all():
            return True
        return False


class FriendRequest(models.Model):

    sender = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=(models.CASCADE), related_name='friend_requests_sent')
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=(models.CASCADE), related_name='friend_requests_received')
    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['sender','receiver'],
                name="unique_friend_request"
            )
        ]

    def __str__(self):
        return self.sender.user_name
    
    def accept(self):
        """Queries the friends list of both the sender and the receiver and adds both
        to their respective friends lists"""
        receiver_friends_list = FriendsList.objects.get(user=self.receiver)
        if receiver_friends_list:
            receiver_friends_list.add_friend(self.sender)    
            sender_friends_list = FriendsList.objects.get(user=self.sender)
            if sender_friends_list:
                sender_friends_list.add_friend(self.receiver)
        self.is_active = False
        self.save()

    def decline(self):
        self.is_active = False
        self.save()

    def cancel(self):
        """
        works like decline, only differs from it in the 
        way it's handled by the app (notifications etc...)
        """
        self.is_active = False

    def renew(self):
        """makes request active again"""
        self.is_active = True
        self.save()

friends/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from .models import FriendRequest, FriendsList

User = get_user_model()

def search_friends(request):
    searched = request.GET.get('searched') or request.POST.get('searched')
    if searched:
        users = User.objects.filter(user_name__contains=searched)
        context = {'users': users,'searched' : searched,}
        return render(request, 'friends/search_friends.html', context)
    else:
        return render(request, 'friends/search_friends.html')

    
def new_friend_request(request, target_id):
    target = User.objects.get(id=target_id)
    user_friends = FriendsList.objects.get(user=request.user).friends.all()
    target_friends = FriendsList.objects.get(user=target).friends.all()
    existing_request = FriendRequest.objects.filter(
        sender=request.user, receiver=target, is_active=True)
    reciprocal_request = FriendRequest.objects.filter(
        sender=target, receiver=request.user, is_active=True)
    inactive_request = FriendRequest.objects.filter(
        sender=request.user, receiver=target, is_active=False).first()
    next_page = request.POST.get('next')
    searched = request.POST.get('searched')

    if target == request.user:
        messages.error(request,
             "¡No puedes enviarte una solicitud de amistad a ti mismo!", extra_tags="friends")

    elif existing_request.exists():
        messages.info(request,
             f'Ya has enviado una solicitud de amistad a {target}.', extra_tags="friends")
    
    elif reciprocal_request.exists():
        messages.info(request, 
            f'{target} ya te ha enviado una solicitud. ¡Revísala!', extra_tags="friends")
    
    elif target in user_friends  or request.user in target_friends:
        messages.info(request,
            f'{target} ya está en tu lista de amigos.', extra_tags="friends")
        
    elif inactive_request:
        messages.success(request, 
                "¡Solicitud de amistad enviada!", extra_tags="friends")
        inactive_request.renew()
        
        
    else:
        FriendRequest.objects.create(sender=request.user, receiver=target)
        messages.success(request, 
                "¡Solicitud de amistad enviada!", extra_tags="friends")
    
    return redirect(f"{next_page}?searched={searched}" or 'blog:blogs_list')

def friends_page(request):
    user = User.objects.get(id=request.user.id)
    user_requests = FriendRequest.objects.filter(receiver=user, is_active=True)
    user_friends = FriendsList.objects.get(user=request.user).friends.all()

    context={
        'list_user': user,
        'user_friends': user_friends,
        'user_requests' : user_requests,
    }
    return render(request, 'friends/friends_page.html', context)

def accept_request(request, fr_request_id):
    fr_request = FriendRequest.objects.get(id=fr_request_id)
    next_page = request.POST.get('next')
    fr_request.accept()
    if next_page:
        messages.success(request, 
            f'{fr_request.sender} y tú ahora sois amigos.', extra_tags="friends")
        return redirect(next_page)
    else:

        return redirect('blog:blogs_list')
    
def decline_request(request, fr_request_id):
    fr_request = FriendRequest.objects.get(id=fr_request_id)
    target = fr_request.sender
    next_page = request.POST.get('next')
    messages.info(request,
            f'Has rechazado la solicitud de amistad de {target}.', extra_tags="friends")
    fr_request.decline()
    if next_page:
        return redirect(next_page)
    else:
        return redirect('blog:blogs_list')
    
def end_friendship(request, removee_id):
    """
    Looks for the correspondent friend request and makes it inactive.
    Then reciprocally eliminates both users from their friends list.
    """
    removee = User.objects.get(id=removee_id)
    remover = User.objects.get(user_name = request.user)
    friend_request_option_1 = FriendRequest.objects.filter(sender=remover, receiver=removee).first()
    friend_request_option_2 = FriendRequest.objects.filter(sender=removee, receiver=remover).first()
    user_friends_list = FriendsList.objects.get(user = remover)

    if removee not in user_friends_list.friends.all():
        messages.info(request, 
            f'{removee} no está en tu lista de amigos.', extra_tags="friends")
        return redirect(next_page or 'blog:blogs_list')
    
    if friend_request_option_1:
        friend_request_option_1.cancel()

    if friend_request_option_2:
        friend_request_option_2.cancel()

    user_friends_list.unfriend(removee)
    messages.info(request, 
        f'{removee} ha sido eliminado de tu lista de amigos.', extra_tags="friends")
    next_page = request.POST.get('next')
    return redirect(next_page or 'blog:blogs_list')
    
        
    

friends/templates/friends/friends_page.html
{% extends 'blog/layout.html' %}

{% block page_header %}


{% endblock page_header %}

{% block content %}

{% if messages %}

    <div>
        {% for message in messages %}
            {% if 'friends' in message.tags %}
                <div class="alert alert-{{ message.level_tag }}">
                    {{message}}
                </div>
            {% endif %}                    
        {% endfor %}
    </div>
{% endif %}

<div class="px-1 px-md-4 py-4 d-flex flex-column centered">
        <h3>  Amigos </h3>
</div>

<div class="p-3 mb-1 blackboard col-md-6 mx-auto">
    <form class="d-flex adjusted" action="{% url 'friends:search_friends' %}" method=POST>
        {% csrf_token %} 

        <input class="form-control me-2" type="search" placeholder="Buscar usuarios" 
        aria-labels="Buscar usuario" name="searched">
        <button class="friends-row-button" type="submit">Buscar</button>
    </form>
    <div class="centered pb-3 mt-3">
        <h4>Lista de amigos</h4>
    </div>
    {% for friend in user_friends %}
    <div class="friends-list pb-2 pt-2">
        <div class="friends-row border-bottom pb-2">
            <div class="left-row">

                <a href="{% url 'accounts:user_profile' friend.id %}">
                    <img class="push-up"src="{{friend.avatar_small}}">
                </a>
                <a href="{% url 'accounts:user_profile' friend.id %}">{{friend.user_name}}</a>
            </div>
            <div>
                <form action="{% url 'friends:end_friendship' friend.id %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ request.path }}">
                    <button class= "friends-row-button ms-auto" 
                    type="submit">Eliminar amigo</button>
                </form>
            </div>
        </div>
    </div>
    {% empty %}
        <p>Aún no tienes amigos</p>
    {% endfor %}
</div>
<div class="p-3 mb-1 blackboard col-md-6 mx-auto my-4">
    <div class="centered pb-3">
        <h4>Solicitudes de amistad</h4>
    </div>
    {% for fr_request in user_requests %}
        <div class="friends-list pb-2 pt-2">
            <div class="friends-row border-bottom pb-2">
                <div class="left-row">
                <a href="{% url 'accounts:user_profile' fr_request.sender.id %}">
                    <img class="push-up" src="{{fr_request.sender.avatar_small}}">
                </a>
                    <p>
                        <a href="{% url 'accounts:user_profile' fr_request.sender.id %}">{{fr_request.sender.user_name}}</a>
                        
                </div>
                <div class="friends-row-buttons">
                    <form action="{% url 'friends:accept_request' fr_request.id %}"
                     method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class= "friends-row-button ms-auto" 
                            type="submit">Aceptar</button>
                    </form>
                    <form action="{% url 'friends:decline_request' fr_request.id %}" 
                    method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="next" value="{{ request.path }}">
                            <button class= "friends-row-button ms-auto" 
                            type="submit">Rechazar</button>
                    </form>
                </div>
            </div>
        </div>
            
        
    {% empty %}
    <p>No tienes solicitudes de amistad pendientes</p>
    {% endfor %}
</div>

{% endblock content %}

friends/templates/friends/search_friends.html
{% extends 'blog/layout.html' %}

{% block page_header %}


{% endblock page_header %}

{% block content %}
{% if messages %}

    <div>
        {% for message in messages %}
            {% if 'friends' in message.tags %}
                <div class="alert alert-{{ message.level_tag }}">
                    {{message}}
                </div>
            {% endif %}                    
        {% endfor %}
    </div>
{% endif %}

<h2 class ="p-3 mb-1 col-md-6 mx-auto centered">Resultados de la búsqueda</h2>
<div class="p-3 mb-1 blackboard col-md-6 mx-auto">
    {% if searched %}
        {% for searched_user in users %}
        <div class="friends-list pb-2 pt-2">
            <div class="friends-row border-bottom pb-2">
                <div>
                    <a href="{% url 'accounts:user_profile' searched_user.id %}">{{searched_user.user_name}}</a>
                </div>
                <div>
                    <form action="{% url 'friends:new_friend_request' searched_user.id %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ request.path }}">
                        <input type="hidden" name="searched" value="{{ searched }}">
                        <button class= "friends-row-button ms-auto" 
                        type="submit">Solicitar amistad</button>
                    </form>
                </div>
            </div>
        {% empty %}
            <h3 class="centered mt-2 mb-2">No hay resultados para la búsqueda.</h3>
        {% endfor %}
    {% else %}
            <h3 class="centered mt-2 mb-2">¡Ups! Parece que no has introducido ninguna búsqueda.</h3>
    {% endif %}
</div>

{% endblock content %}